module.exports = Object.freeze({
    VIDEO_LIST_CHANGED: 'VIDEO_LIST_CHANGED',
    VIDEO_UPLOAD_PROGRESS: 'VIDEO_UPLOAD_PROGRESS',
    VIDEO_STATUS_ENVIANDO: 'ENVIANDO',
    VIDEO_STATUS_ENCODANDO: 'ENCODANDO',
    VIDEO_STATUS_FINALIZADO: 'FINALIZADO'
});